version: '3.8'
services:
  django:
    container_name: sistem_skoring
    command: python manage.py runserver 0.0.0.0:8080
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"