version: '3.8'
services:
  web:
    container_name: web
    command: python manage.py runserver 0.0.0.0:8080
    build:
      context: .
    # env_file:
    #   - .env
    volumes:
      - .:/app
    ports:
      - "8080:8080"